name: build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install build-essential ca-certificates curl jq gnupg2 ca-certificates psmisc procps xz-utils rsync libglib2.0-dev libgpgme-dev libassuan-dev libbtrfs-dev libdevmapper-dev pkg-config


      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Test version
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}
          echo ${{ github.ref }}

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.1'

      - name: Get gopath
        id: get_gopath
        run: echo ::set-output name=GOPATH::$(go env GOPATH)

      - run: go env
      - run: go version

      - name: Build skopeo binary
        run: |
          git clone --verbose --progress --depth 1 --branch ${{ steps.get_version.outputs.VERSION }} https://github.com/containers/skopeo.git ${{ steps.get_gopath.outputs.GOPATH }}/src/github.com/containers/skopeo

          pushd ${{ steps.get_gopath.outputs.GOPATH }}/src/github.com/containers/skopeo &>/dev/null || exit 1
            make bin/skopeo DISABLE_CGO=1
            pushd ./bin &>/dev/null
                tar -cvJf skopeo.tar.xz skopeo
                tar -cvzf skopeo.tar.gz skopeo
            popd &>/dev/null
            ls -l ./bin
          popd &>/dev/null

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "Release skopeo ${{ steps.get_version.outputs.VERSION }}.  \n source: https://github.com/containers/skopeo/releases/tag/${{ steps.get_version.outputs.VERSION }}"
          files: |
            ${{ steps.get_gopath.outputs.GOPATH }}/src/github.com/containers/skopeo/bin/skopeo
            ${{ steps.get_gopath.outputs.GOPATH }}/src/github.com/containers/skopeo/bin/skopeo.tar.xz
            ${{ steps.get_gopath.outputs.GOPATH }}/src/github.com/containers/skopeo/bin/skopeo.tar.gz
            
